// <auto-generated />
using LegoChecksheet.API.Domain;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LegoChecksheet.API.Domain.Migrations
{
    [DbContext(typeof(LegoContext))]
    [Migration("20230122045607_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LegoChecksheet.API.Domain.Models.LegoPiece", b =>
                {
                    b.Property<int>("LegoPieceId")
                        .HasColumnType("int");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ElementId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LegoSetId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumberMissing")
                        .HasColumnType("int");

                    b.Property<bool>("Owned")
                        .HasColumnType("bit");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("LegoPieceId");

                    b.HasIndex("LegoSetId");

                    b.ToTable("LegoPieces");
                });

            modelBuilder.Entity("LegoChecksheet.API.Domain.Models.LegoSet", b =>
                {
                    b.Property<int>("LegoSetId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LegoSetId");

                    b.ToTable("LegoSets");
                });

            modelBuilder.Entity("LegoChecksheet.API.Domain.Models.LegoPiece", b =>
                {
                    b.HasOne("LegoChecksheet.API.Domain.Models.LegoSet", "LegoSet")
                        .WithMany("LegoPieces")
                        .HasForeignKey("LegoSetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LegoSet");
                });

            modelBuilder.Entity("LegoChecksheet.API.Domain.Models.LegoSet", b =>
                {
                    b.Navigation("LegoPieces");
                });
#pragma warning restore 612, 618
        }
    }
}
